### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by Strappazzon** [Strappazzon/PD2-Real-Weapon-Names#13]
We are pushing **the last updates** of Real Weapon Names and we would like to update the **[French](https://github.com/Strappazzon/PD2-Real-Weapon-Names/blob/master/lua/loc/fr.json)**, **[Russian](https://github.com/Strappazzon/PD2-Real-Weapon-Names/blob/master/lua/loc/ru.json)** and **[Spanish](https://github.com/Strappazzon/PD2-Real-Weapon-Names/blob/master/lua/loc/es.json)** localizations as well before releasing the final version of the mod.

Please open a Pull Request when your updated localization file is ready.
@PoorPocketsMcNewHold, @Retreeb, @ernestin12

**Comment by PoorPocketsMcNewHold** [comment]
I'm starting working on it right now ! ![](https://media1.tenor.com/images/b34fcf12782373b51f99ea549751c772/tenor.gif?itemid=7176533)
