### ISSUE TITLE
Localization Update v3.1.0

### ISSUE THREAD

**Issue by shinrax2** [Strappazzon/PD2-Real-Weapon-Names#17]
Hi
I made additions to RWN and the localizations need updates.
Thanks in advance for your work :)

Italian: @Strappazzon 
French: @PoorPocketsMcNewHold 
Russian: @OverkeelSpy 

<details>
    <pre>bm_wp_upg_fl_x400v</pre>
    <summary>Changed IDs:</summary>
</details>

<details>
    <pre>
bm_w_beer
bm_w_x_beer
bm_w_czech
bm_w_x_czech
bm_w_stech
bm_w_x_stech

bm_wp_upg_o_rms
bm_wp_upg_o_rikt
bm_wp_upg_ns_typhoon

bm_wp_upg_g_m4_surgeon
bm_wp_upg_ns_ass_smg_v6
bm_wp_upg_o_fc1
bm_wp_upg_o_uh
bm_wp_upg_o_bmg
bm_wpn_fps_upg_o_sig

bm_wp_beer_b_robo
bm_wp_beer_g_robo
bm_wp_beer_g_lux
bm_wp_beer_s_std
bm_wp_beer_m_extended

bm_wp_czech_b_long
bm_wp_czech_g_sport
bm_wp_czech_g_luxury
bm_wp_czech_s_standard
bm_wp_czech_m_extended

bm_wp_stech_b_long
bm_wp_stech_g_tactical
bm_wp_stech_g_luxury
bm_wp_stech_s_standard
bm_wp_stech_m_extended
    </pre>
    <summary>New IDs:</summary>
</details>

---

**Edit by @Strappazzon:** Formatting and capitalization

**Comment by Strappazzon** [comment]
https://github.com/Strappazzon/PD2-Real-Weapon-Names/commit/2e8631996ad343f5b1a95597266d96c971aa8947
