### ISSUE TITLE
Names for akimbo shotguns not showing

### ISSUE THREAD

**Issue by Nickisnthere** [Strappazzon/PD2-Real-Weapon-Names#25]
The names for the akimbo shotguns arent showing up
![image_2021-12-29_214601](https://user-images.githubusercontent.com/85907040/147717533-a957874f-7e52-478c-9ab3-d123a0365d1e.png)

**Comment by shinrax2** [comment]
i will look into that

**Comment by shinrax2** [comment]
@Nickisnthere 
i was unable to reproduce your results and also according to your screenshots the names for akimbo shotguns load

could please elaborate further what you mean by not working?

**Comment by shinrax2** [comment]
closed due to inactivity
